### ISSUE TITLE
QA: CMS App

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#314]
@orzechdev please write down scenarios for QA testing

**Comment by michalina-graczyk** [comment]
![image](https://user-images.githubusercontent.com/25908728/227875560-54f447b1-f947-45b7-94b2-a5b21f48091b.png)

**Comment by michalina-graczyk** [comment]
Confirmation popups are missed, when I am saving sth I am expecting a popup 'Your changes are saved or sth' 

https://user-images.githubusercontent.com/25908728/227884724-eaf305b2-82dc-4f50-bf38-41b2e3571053.mp4

**Comment by michalina-graczyk** [comment]
![image](https://user-images.githubusercontent.com/25908728/227903179-fe082b6a-937c-47e4-a31e-31d03e7bcea3.png)

**Comment by michalina-graczyk** [comment]
Missed validation on providers 
Steps:
1. Go to CMS app -> providers tab
2. Pick any providers
3. Type random input
4. Click 'Save'
Result:
There is no validation provider, you can put anything. 
![image](https://user-images.githubusercontent.com/25908728/227932313-8f4c2f35-f693-4220-880b-4321fa35910b.png)

**Comment by michalina-graczyk** [comment]
**Can't see any results in the providers**

1. Go to apps -> CMS app 
2. Select a channel 
3. Set to active all CMS providers
4. Save
5. Go to providers tab
6. Select each of providers and fill with all required data 
  6.1 In each of CMS privders do 

> Go to your CMS website and prepare product variant model shape with:
string fields: saleor_id, name, product_id, product_name, product_slug,
JSON fileds: channels.

7. Save
8. Go to Product
9. In Availability area select the same channel as in 2 step
10. In Variants table add new variant and select it as a avaliable for your channel 
11. Click save
Expexted result: Added Variant is visible in CMS providers
![image](https://user-images.githubusercontent.com/25908728/228196036-1e7a79f2-62a4-4599-9607-d976a8d9a8fc.png)

Current result: I can't see changes in CMS providers.

**Comment by orzechdev** [comment]
Can't see any results in the providers ->

Issues solved by:
- updated wrong configuration for DatoCMS, Model ID was set as Project ID
- updated wrong configuration of product channel availability caused Saleor didn't take into account variant channel availability and didn't send an event to the app webhooks
- updated wrong definition of model fields in Contentful, Fields IDs were camelCase instead as snake_case

Actionable items:
- everything is fine in the app code, if it is possible improve instructions taking previous points into account

**Comment by michalina-graczyk** [comment]
Tested, please let me know when reported issues will be fixed then I'll re-test it.

**Comment by michalina-graczyk** [comment]
I still have problem that I don't have the 'edit' button on the content type builder page 
![image](https://user-images.githubusercontent.com/25908728/234581276-5f342a35-2fd1-46a2-9879-8004b21e97b6.png)

**Comment by orzechdev** [comment]
I tested it locally as well and I have the 'edit' button on the content type builder page
<img width="1279" alt="Screenshot 2023-04-26 at 15 03 14" src="https://user-images.githubusercontent.com/9825562/234583342-8602cf66-8522-445b-a3e9-8af787d141a6.png">

**Comment by michalina-graczyk** [comment]
I have created a new project and the edit button was visible, so I ve checked sync foor strapi and it works correctly ✅

**Comment by orzechdev** [comment]
Can't find what could be the reason of this inconsistency. Permissions maybe, which may disable some sort of UI.  Anyway it's hard to update instructions for that case as no other place shows plural ID of content type.
